apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: stage

images:
- name: chukmunnlee/dov-bear
  newName: chukmunnlee/NEW_IMAGE_NAME
  digest: NEW_DIGEST
