apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  commit: __COMMIT_HASH__

buildMetadata: [managedByLabel]

images:
- name: chukmunnlee/dov-bear
  newName: chukmunnlee/__NEW_IMAGE_NAME__
  digest: __NEW_DIGEST__
