---
apiVersion: v1
kind: ConfigMap
metadata:
   name: dov-cm
   labels:
      name: dov-cm
data:
   INSTANCE_NAME: k8s-dov

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: dov-deploy
   labels:
      name: dov-deploy
spec:
   replicas: 2
   selector:
      matchLabels:
         name: dov-pod
   template:
      metadata:
         name: dov-pod
         labels:
            name: dov-pod
      spec:
         containers:
         - name: dov-container
           image: chukmunnlee/dov-bear:v2
           imagePullPolicy: IfNotPresent
           ports:
           - containerPort: 3000
           env:
           - name: INSTANCE_HASH
             valueFrom:
                fieldRef:
                   fieldPath: status.podIP
           envFrom:
           - configMapRef:
              name: dov-cm

--- 
apiVersion: v1
kind: Service
metadata:
   name: dov-svc
   labels:
      name: dov-svc
spec:
   type: ClusterIP
   selector:
      name: dov-pod
   ports:
   - port: 3000
     targetPort: 3000
