---
apiVersion: v1
kind: ConfigMap
metadata:
   name: dov-cm
   labels:
      name: dov-cm
data:
   INSTANCE_NAME: k8s-dov

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: dov-deploy
   labels:
      name: dov-deploy
spec:
   replicas: 2
   selector:
      matchLabels:
         name: dov-pod
   template:
      metadata:
         name: dov-pod
         labels:
            name: dov-pod
      spec:
         containers:
         - name: dov-container
           image: chukmunnlee/dov-bear:v4
           imagePullPolicy: IfNotPresent
           env:
           - name: INSTANCE_HASH
             valueFrom:
                fieldRef:
                   fieldPath: status.podIP
           envFrom:
           - configMapRef:
              name: dov-cm
           ports:
           - containerPort: 3000
           - name: metrics 
             containerPort: 3100

--- 
apiVersion: v1
kind: Service
metadata:
   name: dov-svc
   labels:
      name: dov-svc
spec:
   type: ClusterIP
   selector:
      name: dov-pod
   ports:
   - port: 3000
     targetPort: 3000
   - name: metrics 
     port: 3100
     targetPort: 3100

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: dov-ing
   labels:
      name: dov-ing
spec:
   ingressClassName: nginx
   rules:
     # change this 
   - host: dov-192.168.39.13.nip.io
     http:
        paths:
        - path: /
          pathType: Prefix
          backend:
             service:
                name: dov-svc
                port: 
                  number: 3000
